### PR TITLE
Update snapd-2.44.5.ebuild

### PR DESCRIPTION
**Pull request by necrose99**
append app-admin/openrc-settingsd unit runner for openrc..

### CODE REVIEW

**Comment by zigford** [comment]
Does snapd work on openrc with only this change?

**Comment by necrose99** [comment]
[snapd-units.converted.zip](https://github.com/zigford/snapd/files/5170472/snapd-units.converted.zip)
dumped [snapd-deb](https://packages.debian.org/sid/devel/snapd) for units
(https://github.com/zigford/snapd/issues/7) (https://github.com/goose121/initify) ,/inf..pl *.service wala out openrc units,,, 

I belive with the openrc-settingsd its a shim for openrc to run units from systemd USE=systemd 

or if you just converted to systemd <USE=systemd  openrc-settingsd >
 likewise ..  it can run the old openrc scripts on systemd as a compatibility  layer. 

either way should be doable.

**Comment by necrose99** [comment]
Unfortunately testing , they have systemd really dugin good, wich is a shame..

**Comment by zigford** [comment]
Yes, deeply embedded. It's going to require a herculean effort to undug it.

**Pull request closed without merging**
